name: Master CI/CD

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'
jobs:
  deliver:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Push to GitHub Package Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: tiltcamp/ruby-alpine-passenger/ruby-alpine-passenger
          tags: latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: tiltcamp/ruby-alpine-passenger
          tags: latest
